# Generated by Django 4.1.7 on 2023-03-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('bio', models.CharField(max_length=200)),
                ('college', models.TextField()),
                ('country', models.TextField()),
                ('createdAt', models.TextField()),
                ('dob', models.TextField()),
                ('email', models.TextField()),
                ('face_detection_probabilities', models.TextField()),
                ('gender', models.TextField()),
                ('height', models.FloatField()),
                ('insta_username', models.FloatField()),
                ('interests', models.TextField()),
                ('is_habit_drink', models.TextField()),
                ('is_habit_smoke', models.TextField()),
                ('is_verified', models.BooleanField()),
                ('mobile', models.BigIntegerField()),
                ('name', models.TextField()),
                ('status', models.BooleanField()),
                ('type', models.TextField()),
                ('updatedAt', models.TextField()),
                ('verified_at', models.TextField()),
                ('what_to_find', models.TextField()),
                ('who_to_date', models.TextField()),
                ('is_subscribed', models.BooleanField()),
            ],
        ),
    ]
