# Generated by Django 4.1.7 on 2023-03-04 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='insta_username',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_subscribed',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='is_verified',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Swipes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_like_unlike_at', models.TextField()),
                ('first_msg', models.TextField(max_length=200)),
                ('first_type', models.TextField()),
                ('is_unmatch', models.TextField()),
                ('like_count', models.BigIntegerField()),
                ('p1_extend_at', models.TextField()),
                ('p2_extend_at', models.TextField()),
                ('second_like_unlike_at', models.TextField()),
                ('second_msg', models.TextField()),
                ('second_type', models.TextField()),
                ('unmatch_on', models.TextField()),
                ('p1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes1', to='final.person')),
                ('p2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes2', to='final.person')),
            ],
        ),
    ]
