# Generated by Django 4.1.7 on 2023-03-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final', '0002_alter_person_height_alter_person_insta_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('height', models.TextField()),
                ('is_habit_drink', models.TextField()),
                ('is_habit_smoke', models.TextField()),
                ('is_verified', models.TextField()),
                ('what_to_find', models.TextField()),
                ('who_to_date', models.TextField()),
                ('score', models.TextField()),
            ],
        ),
    ]
